# DATA_ROOT environment variable based on contents of .env
version: "3.9"
services:
  server: # back-end nodejs
    build: ./server
    restart: always
    environment:
      - DB_USER=???
      - DB_PASS=???
      - DB_NAME=???
      - DB_HOST=???

  client: # front-end vuejs ran with nginx
    build: ./client
    restart: always
    # nginx static files
    ports:
      - "8083:80" # port 8083 on host maps to port 80 on container
    depends_on:
      - server
